apiVersion: {{ .Values.apiVersions.daemonset }}
kind: DaemonSet
metadata:
  name: filebeat
  annotations:
    scheduler.alpha.kubernetes.io/nodes-critical: ""
  namespace: {{ template "filebeat.namespace" . }}
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ template "filebeat.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      priorityClassName: "system-node-critical"
      containers:
      - name: filebeat
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: IGNORE_OLDER
          value: {{ .Values.daemonset.ignoreOlder }}
        - name: FIELDS_UNDER_ROOT
          value: {{ quote .Values.daemonset.fieldsUnderRoot }}
        securityContext: {{ toYaml ( .Values.daemonset.securityContext ) | nindent 10 }}
        resources: {{ toYaml ( .Values.daemonset.resources ) | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      {{- range .Values.daemonset.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: {{ .readOnly }}
          subPath: {{ .subPath }}
      {{- end }}
      {{- if .Values.daemonset.tolerations }}
      tolerations:
{{ toYaml .Values.daemonset.tolerations | indent 6 }}
      {{- end }}
      {{- if .Values.daemonset.priorityClassName }}
      priorityClassName: {{ .Values.daemonset.priorityClassName }}
      {{- end }}
      volumes:
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
    {{- range .Values.daemonset.volumes }}
      - name: {{ .name }}
        configMap:
          defaultMode: {{ .configMap.defaultMode }}
          name: {{ .configMap.name }}
    {{- end }}