{{- if .Values.managedServiceAccount }}
apiVersion: {{ .Values.apiVersions.serviceAccount }}
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: {{ template "filebeat.namespace" . }}
  labels:
    k8s-app: filebeat
{{- end -}}